app: 
  name: my-springboot2-example1

#logging      
logging: 
  config: classpath:log/logback-spring.xml
  
#spring
spring: 
  profiles: 
    active: dev 
    
server:
  port: 8080
  servlet: 
    context-path: /${app.name}
  connection-timeout:
  compression:
    enabled: true
  error:
    path: /error
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800 # tomcat最大线程数，默认为200
    basedir: /logs/${app.name}  # 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
    accesslog:
      enabled: true
      